apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  selector:
    matchLabels:
      app: thanos-query
  replicas: 1
  template:
    metadata:
      labels:
        app: thanos-query
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
        - name: thanos-query
          image: improbable/thanos:v0.4.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "query"
            - "--cluster.disable"
            - "--query.auto-downsampling"
            - "--query.partial-response"
            - "--query.replica-label=replica"
            - "--grpc-address=0.0.0.0:10901"
            - "--http-address=0.0.0.0:10902"
            - "--store=dns+thanos-sidecar-grpc.monitoring.svc.cluster.local:10901"
            - "--store=dns+thanos-store-grpc.monitoring.svc.cluster.local:10901"
            - "--log.level=debug"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          #TODO readinessProbe:
          #TODO livenessProbe:
