# See https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval:     10s
  evaluation_interval: 60s

  external_labels:
    dc: 'mydatacenter'
    app: 'myapp'
    env: 'prod'

scrape_configs:
  - job_name: 'file_sd_targets'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.json
