apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos-store
spec:
  selector:
    matchLabels:
      app: thanos-store
  replicas: 1
  template:
    metadata:
      labels:
        app: thanos-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10902"
    spec:
      containers:
        - name: thanos-query
          image: improbable/thanos:v0.3.0
          imagePullPolicy: "IfNotPresent"
          args:
            - "store"
            - "--cluster.disable"
            - "--grpc-address=0.0.0.0:10901"
            - "--http-address=0.0.0.0:10902"
            - "--data-dir=/store"
            - "--objstore.config-file=/creds/bucket_config"
            - "--log.level=debug"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          #TODO readinessProbe:
          #TODO livenessProbe:
          volumeMounts:
          - name: data
            mountPath: /store
          - name: creds
            mountPath: /creds
            readOnly: true
      volumes:
      - name: data
        emptyDir: {}
      - name: creds
        secret:
          secretName: s3-creds