kind: Service
apiVersion: v1
metadata: 
  name: thanos-store
  namespace: monitoring
  labels: 
    app: thanos-store
spec: 
  #TODO type: ClusterIP
  type: NodePort
  ports: 
    - name: store-http
      port: 10902
      protocol: TCP
      targetPort: 10902
  selector: 
    app: thanos-store
---
# HeadlessService
kind: Service
apiVersion: v1
metadata:
  name: thanos-store-grpc
  namespace: monitoring
  labels: 
    app: thanos-stores
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: store-grpc
    port: 10901
    protocol: TCP
    targetPort: 10901
  selector:
    app: thanos-store