global:
  external_labels:
    cluster: cluster
    prometheus: prom-2
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - "localhost:9090"
- job_name: thanos-sidecar
  scrape_interval: 5s
  static_configs:
  - targets:
    - "sidecar2:10902"
- job_name: thanos-store
  scrape_interval: 5s
  static_configs:
  - targets:
    - "store:10902"
- job_name: thanos-query
  scrape_interval: 5s
  static_configs:
  - targets:
    - "query1:10902"
    - "query2:10902"
    - "query3:10902"
