global:
  external_labels:
    company: acme 
    cluster: c3-cluster
    prometheus: c3-prom
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - "localhost:9090"
- job_name: thanos-sidecar
  scrape_interval: 5s
  static_configs:
  - targets:
    - "c3-sidecar:10902"
- job_name: thanos-store
  scrape_interval: 5s
  static_configs:
  - targets:
    - "c3-store:10902"
- job_name: thanos-query
  scrape_interval: 5s
  static_configs:
  - targets:
    - "c3-query:10902"
