apiVersion: 1
datasources:
- name: influxdb-all
  type: influxdb
  access: proxy
  org_id: 1
  url: http://meta-influxdb-all:8086
  password: pass
  user: user
  database: prom
  basic_auth:
  basic_auth_user:
  basic_auth_password:
  with_credentials:
  is_default: false
  version: 1
  editable: true
- name: influxdb-selected
  type: influxdb
  access: proxy
  org_id: 1
  url: http://meta-influxdb-selected:8086
  password: pass
  user: user
  database: prom
  basic_auth:
  basic_auth_user:
  basic_auth_password:
  with_credentials:
  is_default: false
  version: 1
  editable: true
